apiVersion: apps/v1
kind: Deployment
metadata:
  name: tv
  labels:
    app: tv
spec:
#  replicas: 10
  selector:
    matchLabels:
      app: tv
  template:
    metadata:
      labels:
        app: tv
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /var/www/html/
          name: wp
        - mountPath: /etc/nginx/conf.d/
          name: conf
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
      - name: php-fpm
        image: hiakki/php7.3-fpm_mysql
        volumeMounts:
        - mountPath: /var/www/html/
          name: wp
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 10m
      volumes:
      - name: wp
        hostPath:
          path: /home/kube/tricksvibe/wordpress
      - name: conf
        hostPath:
          path: /home/kube/tricksvibe/nginx
