apiVersion: v1
kind: Service              
metadata:
  name: my-nginx

spec:
  type: LoadBalancer
  externalIPs:
  - ext_ip
  ports:
  - port: ext_port_nginx
    protocol: TCP
    targetPort: 80
    nodePort: node_port_nginx
  selector:
    app: my-nginx
