apiVersion: v1
kind: ConfigMap
metadata:
  name: tv-nginx
  labels:
    tier: backend
data:
  config : |
    upstream fastcgi_backend {
            server ext_ip:ext_port_php;
    }
 
    # Eliminate Render-Blocking Resources
    map $http_cookie $resources {
        "~*session=1" "";
        default "</style.css>; as=style; rel=preload, </font.css>; as=style; rel=preload";
    }


    # WebP Settings 
    map $http_accept $webp_suffix {
        default "";
        "~*webp" ".webp";
    }
 
    server {
        listen 80;
        listen [::]:80;
        
        server_name _;

        server_tokens off;
        # Enabling CSP
        add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'" always;

        # Enabling HSTS
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains" always;

        # Enabling HTTP Public Key Pinning
        add_header Public-Key-Pins "pin-sha256='X3pGTSOuJeEVw989IJ/cEtXUEtv52zs1TZQrU06KUKg='; pin-sha256='MHJYVThihUrJcxW6wcqyOISTXIsInsdj3xK8QrZbHec='; pin-sha256='isi41AizREkLvvft0IRW4u3XMFR2Yg7bvrF7padyCJg='; includeSubdomains; max-age=2592000" always;

        # Enabling X-Frame-Options
        add_header X-Frame-Options "SAMEORIGIN" always;

        # Enabling X-XSS-Protection
        add_header X-Xss-Protection "1; mode=block" always;

        # Enabling X-Content-Type-Options
        add_header X-Content-Type-Options "nosniff" always;

        root /usr/app/;
        index index.php index.html;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Redirect all HTTP to HTTPS
        if ($http_x_forwarded_proto != "https") {
            rewrite ^(.*)$ https://$host$REQUEST_URI permanent;
        }
        
        location ~ \.php$ {
            root /usr/app/;
            index index.php index.html;
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass fastcgi_backend;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
        # Add Expires Headers
        location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
            expires 30d;
            add_header Pragma public;
            add_header Cache-Control "public";
        }

        # WebP Settings 
        location ~* ^(/wp-content/.+)\.(png|jpe?g)$ {
            set $base $1;
            set $webp_uri $base$webp_suffix;
            set $webp_old_uri $base.$2$webp_suffix;
            set $root "/usr/app/wp-content/";
            root $root;
            add_header Vary Accept;
            if ( !-f $root$webp_uri ) {
                add_header X_WebP_SP_Miss $root$webp_uri;
            }
            try_files $webp_uri $webp_old_uri $uri =404;
        }

        # Below are the settings for Wordpress Permalink setup
        location ~ ^(/[^/]+/)?files/(.+) {
            access_log off;     log_not_found off; expires max;
        }

        #avoid php readfile()
        location ^~ /blogs.dir {
            internal;
            alias /var/www/example.com/htdocs/wp-content/blogs.dir ;
            access_log off;     log_not_found off; expires max;
        }

        if (!-e $request_filename) {
            rewrite /wp-admin$ $scheme://abcd$uri/ permanent;
            rewrite ^(/[^/]+)?(/wp-.*) $2 last;
            rewrite ^(/[^/]+)?(/.*\.php) $2 last;
        }

        location / {
            try_files $uri $uri/ /index.php?$args ;
            # Eliminate Render-Blocking Resources 
            add_header Set-Cookie "session=1";
            add_header Link $resources;
        }

    }
