apiVersion: v1
kind: Service              
metadata:
  name: tv-php

spec:
  type: LoadBalancer
  externalIPs:
  - 10.7.3.68
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30421
  selector:
    app: tv-php
