apiVersion: apps/v1
kind: Deployment
metadata:
  name: tv-php
  labels:
    app: tv-php
spec:
  selector:
    matchLabels:
      app: tv-php
  template:
    metadata:
      labels:
        app: tv-php
    spec:
      containers:
      - name: tv-php
        image: hiakki/tv-php
        volumeMounts:
        - mountPath: /usr/local/etc/php-fpm.d/
          name: www-conf
        - mountPath: /usr/local/etc/php/
          name: php-ini
        - mountPath: /usr/app/
          name: data
        resources:
          requests:
            cpu: 100m
      volumes:
      - name: www-conf
        configMap:
          name: tv-php-www-conf
          items:
          - key: wwwconf
            path: site.conf
      - name: php-ini
        configMap:
          name: tv-php-ini
          items:
          - key: phpini
            path: php.ini
      - name: data
        hostPath:
          path: /home/kube/app/
#      - name: data
#        persistentVolumeClaim:
#          claimName: tv-app
#      - name: data
#        awsElasticBlockStore:
#          volumeID: vol-022dd5f42aeee337b
#          fsType: ext4

