apiVersion: v1
kind: Service              
metadata:
  name: hd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer
  ports:
  - port: 81
    protocol: TCP
    targetPort: 80
    nodePort: 30421
  selector:
    app: hd
