apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php
  labels:
    app: my-php
spec:
  selector:
    matchLabels:
      app: my-php
  template:
    metadata:
      labels:
        app: my-php
    spec:
      containers:
      - name: my-php
        image: hiakki/my-php
        volumeMounts:
#         In below lines, I am replacing all files in dir php-fpm.d with www.conf only
        - name: www-conf
          mountPath: /usr/local/etc/php-fpm.d/
          subPath: www.conf
#         In below lines, I am creating php.ini file without removing or replacing any files or dirs
        - name: php-ini
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
        - mountPath: /usr/app/
          name: data
        resources:
          requests:
            cpu: 500m
      volumes:
      - name: www-conf
        configMap:
          name: my-php-www-conf
      - name: php-ini
        configMap:
          name: my-php-ini
      - name: data
        hostPath:
          path: /home/kube/app/
#      - name: data
#        persistentVolumeClaim:
#          claimName: my-app
#      - name: data
#        awsElasticBlockStore:
#          volumeID: vol-022dd5f42aeee337b
#          fsType: ext4

