apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-php
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-php
  minReplicas: 10
  maxReplicas: 20
  targetCPUUtilizationPercentage: 75
