apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php
  labels:
    app: my-php
spec:
  selector:
    matchLabels:
      app: my-php
  template:
    metadata:
      labels:
        app: my-php
    spec:
      containers:
      - name: my-php
        image: hiakki/my-php
        volumeMounts:
        - mountPath: /usr/app/
          name: data
        resources:
          requests:
            cpu: 100m
      volumes:
      - name: data
        hostPath:
          path: /home/kube/app/my/
#      - name: data
#        persistentVolumeClaim:
#          claimName: my-app
#      - name: data
#        awsElasticBlockStore:
#          volumeID: vol-022dd5f42aeee337b
#          fsType: ext4

