apiVersion: v1
kind: Service              
metadata:
  name: my-php

spec:
  type: LoadBalancer
  externalIPs:
  - ext_ip
  ports:
  - port: ext_port_php
    protocol: TCP
    targetPort: 9000
    nodePort: node_port_php
  selector:
    app: my-php
