apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
    role: master
    tier: backend
  name: redis-master
spec:
  type: LoadBalancer
  externalIPs:
  - 172.31.11.156
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 30379
  selector:
    app: redis
    role: master
    tier: backend
status:
  loadBalancer: {}
