apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: redis
    role: master
    tier: backend
  name: redis-master
spec:
  containers:
  - env:
    - name: REDIS_PASS
      value: greenpaper
    image: redis:alpine3.11
    name: redis-master
#    args: ["--requirepass", "$(REDIS_PASS)", "--appendonly", "yes", "--save", "900", "1", "--save", "300", "10", "--save", "60", "10000"]
    args: ["--requirepass", "$(REDIS_PASS)", "--save", "900", "1", "--save", "300", "10", "--save", "60", "10000"]
    ports:
    - containerPort: 6379
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  nodeSelector:
    type: master_service
  tolerations:
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
