apiVersion: v1
kind: Service              
metadata:
  name: green
spec:
  externalIPs:
  - masterIP
  ports:
  - port: 81               
    protocol: TCP          
    targetPort: 81
  selector:                
    app: green
