apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: green
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: green
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
