apiVersion: v1
kind: Service              
metadata:
  name: green
spec:
  externalIPs:
  - 192.168.1.8
  ports:
  - port: 81               
    protocol: TCP          
    targetPort: 81
  selector:                
    app: green
