apiVersion: v1
kind: Service              
metadata:
  name: php

spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.1.18
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
#    nodePort: 30420
  selector:
    app: php
