apiVersion: v1
kind: Service              
metadata:
  name: tv

spec:
  type: LoadBalancer
  externalIPs:
  - masterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30420
  selector:
    app: tv
