apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tv
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
