apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blue
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
