apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
spec:
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/app/
          name: wp
        - mountPath: /etc/nginx/conf.d/
          name: conf
        - mountPath: /var/log/nginx/
          name: logs
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
      - name: php-fpm
        image: hiakki/php7.3-fpm_mysql
        volumeMounts:
        - mountPath: /usr/app/
          name: wp
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 10m
      volumes:
      - name: wp
        hostPath:
          path: /home/kube/tricksvibe/wordpress
      - name: conf
        hostPath:
          path: /home/kube/tricksvibe/nginx/conf.d
      - name: logs
        hostPath:
          path: /home/kube/tricksvibe/nginx/logs

