apiVersion: v1
kind: Service              
metadata:
  name: blue
spec:
  type: LoadBalancer
  externalIPs:
  - masterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blue
